package xjdf4s.codec.json

import io.circe.{Decoder, Json}
import io.circe.syntax.*
import xjdf4s.codec.json.JsonSpecialCodecs.given
import xjdf4s.messaging.*
import xjdf4s.model.*
import xjdf4s.model.resources.*

/** GENERATED registry: JSON dispatch tables for the open substitution points. Every entry summons the
 *  Encoder/Decoder of the type - hand-written where the JSON shape is special (the slice codecs), derived
 *  otherwise. Regenerate with tools/gen-json-codecs.py when the model grows.
 *
 *  Deferred until their hand codecs land: Assembly, LooseBindingParams (payload-enum resources),
 *  FeedingParams (embeds CollatingItem), BindingIntent/ColorIntent/AssemblingIntent (payload-enum intents),
 *  CommandModifyQueueEntry/CommandSubmitQueueEntry (embed deferred params); the foreign message carriers
 *  stay rejected by design.
 */
object JsonRegistry:

  val resourceNames: Set[String] = Set(
    "ApprovalDetails",
    "ApprovalParams",
    "Assembly",
    "BarcodeCompParams",
    "BarcodeReproParams",
    "BendingParams",
    "BinderySignature",
    "BlockPreparationParams",
    "BoxFoldingParams",
    "BoxPackingParams",
    "Bundle",
    "BundlingParams",
    "CaseMakingParams",
    "CasingInParams",
    "Color",
    "ColorCorrectionParams",
    "ColorSpaceConversionParams",
    "ColorantControl",
    "Component",
    "Contact",
    "Content",
    "ConventionalPrintingParams",
    "CoverApplicationParams",
    "CreasingParams",
    "CustomerInfo",
    "CuttingParams",
    "DeliveryParams",
    "DevelopingParams",
    "Device",
    "DieLayout",
    "DieLayoutProductionParams",
    "DigitalPrintingParams",
    "EmbossingParams",
    "EndSheetGluingParams",
    "ExposedMedia",
    "FeedingParams",
    "FoldingParams",
    "FontPolicy",
    "GluingParams",
    "HeadBandApplicationParams",
    "HoleMakingParams",
    "ImageCompressionParams",
    "ImageEnhancementParams",
    "ImageSetterParams",
    "Ink",
    "InkZoneCalculationParams",
    "InkZoneProfile",
    "InsertingParams",
    "InterpretingParams",
    "JacketingParams",
    "LabelingParams",
    "LaminatingParams",
    "Layout",
    "LayoutElementProductionParams",
    "LayoutShift",
    "LooseBindingParams",
    "ManualLaborParams",
    "Media",
    "MiscConsumable",
    "NodeInfo",
    "PDLCreationParams",
    "Pallet",
    "PalletizingParams",
    "PerforatingParams",
    "PreflightParams",
    "PreflightReport",
    "Preview",
    "PreviewGenerationParams",
    "PrintCondition",
    "QualityControlParams",
    "QualityControlResult",
    "RasterReadingParams",
    "RegisterMark",
    "RenderingParams",
    "RunList",
    "ScreeningParams",
    "SeparationControlParams",
    "Shape",
    "ShapeCuttingParams",
    "ShapeDef",
    "ShapeDefProductionParams",
    "SheetOptimizingParams",
    "SheetOptimizingReport",
    "ShrinkingParams",
    "SpinePreparationParams",
    "SpineTapingParams",
    "StackingParams",
    "StitchingParams",
    "StrappingParams",
    "ThreadSealingParams",
    "ThreadSewingParams",
    "Tool",
    "TransferCurve",
    "TrappingParams",
    "TrimmingParams",
    "UsageCounter",
    "VarnishingParams",
    "VerificationParams",
    "VerificationResult",
    "WebInlineFinishingParams",
    "WindingParams",
    "WrappingParams",
  )

  val resourceEncoders: Map[String, SpecificResource => Json] = Map(
    "ApprovalDetails" -> (value => value.asInstanceOf[ApprovalDetails].asJson),
    "ApprovalParams" -> (value => value.asInstanceOf[ApprovalParams].asJson),
    "Assembly" -> (value => value.asInstanceOf[Assembly].asJson),
    "BarcodeCompParams" -> (value => value.asInstanceOf[BarcodeCompParams].asJson),
    "BarcodeReproParams" -> (value => value.asInstanceOf[BarcodeReproParams].asJson),
    "BendingParams" -> (value => value.asInstanceOf[BendingParams].asJson),
    "BinderySignature" -> (value => value.asInstanceOf[BinderySignature].asJson),
    "BlockPreparationParams" -> (value => value.asInstanceOf[BlockPreparationParams].asJson),
    "BoxFoldingParams" -> (value => value.asInstanceOf[BoxFoldingParams].asJson),
    "BoxPackingParams" -> (value => value.asInstanceOf[BoxPackingParams].asJson),
    "Bundle" -> (value => value.asInstanceOf[Bundle].asJson),
    "BundlingParams" -> (value => value.asInstanceOf[BundlingParams].asJson),
    "CaseMakingParams" -> (value => value.asInstanceOf[CaseMakingParams].asJson),
    "CasingInParams" -> (value => value.asInstanceOf[CasingInParams].asJson),
    "Color" -> (value => value.asInstanceOf[Color].asJson),
    "ColorCorrectionParams" -> (value => value.asInstanceOf[ColorCorrectionParams].asJson),
    "ColorSpaceConversionParams" -> (value => value.asInstanceOf[ColorSpaceConversionParams].asJson),
    "ColorantControl" -> (value => value.asInstanceOf[ColorantControl].asJson),
    "Component" -> (value => value.asInstanceOf[Component].asJson),
    "Contact" -> (value => value.asInstanceOf[Contact].asJson),
    "Content" -> (value => value.asInstanceOf[Content].asJson),
    "ConventionalPrintingParams" -> (value => value.asInstanceOf[ConventionalPrintingParams].asJson),
    "CoverApplicationParams" -> (value => value.asInstanceOf[CoverApplicationParams].asJson),
    "CreasingParams" -> (value => value.asInstanceOf[CreasingParams].asJson),
    "CustomerInfo" -> (value => value.asInstanceOf[CustomerInfo].asJson),
    "CuttingParams" -> (value => value.asInstanceOf[CuttingParams].asJson),
    "DeliveryParams" -> (value => value.asInstanceOf[DeliveryParams].asJson),
    "DevelopingParams" -> (value => value.asInstanceOf[DevelopingParams].asJson),
    "Device" -> (value => value.asInstanceOf[Device].asJson),
    "DieLayout" -> (value => value.asInstanceOf[DieLayout].asJson),
    "DieLayoutProductionParams" -> (value => value.asInstanceOf[DieLayoutProductionParams].asJson),
    "DigitalPrintingParams" -> (value => value.asInstanceOf[DigitalPrintingParams].asJson),
    "EmbossingParams" -> (value => value.asInstanceOf[EmbossingParams].asJson),
    "EndSheetGluingParams" -> (value => value.asInstanceOf[EndSheetGluingParams].asJson),
    "ExposedMedia" -> (value => value.asInstanceOf[ExposedMedia].asJson),
    "FeedingParams" -> (value => value.asInstanceOf[FeedingParams].asJson),
    "FoldingParams" -> (value => value.asInstanceOf[FoldingParams].asJson),
    "FontPolicy" -> (value => value.asInstanceOf[FontPolicy].asJson),
    "GluingParams" -> (value => value.asInstanceOf[GluingParams].asJson),
    "HeadBandApplicationParams" -> (value => value.asInstanceOf[HeadBandApplicationParams].asJson),
    "HoleMakingParams" -> (value => value.asInstanceOf[HoleMakingParams].asJson),
    "ImageCompressionParams" -> (value => value.asInstanceOf[ImageCompressionParams].asJson),
    "ImageEnhancementParams" -> (value => value.asInstanceOf[ImageEnhancementParams].asJson),
    "ImageSetterParams" -> (value => value.asInstanceOf[ImageSetterParams].asJson),
    "Ink" -> (value => value.asInstanceOf[Ink].asJson),
    "InkZoneCalculationParams" -> (value => value.asInstanceOf[InkZoneCalculationParams].asJson),
    "InkZoneProfile" -> (value => value.asInstanceOf[InkZoneProfile].asJson),
    "InsertingParams" -> (value => value.asInstanceOf[InsertingParams].asJson),
    "InterpretingParams" -> (value => value.asInstanceOf[InterpretingParams].asJson),
    "JacketingParams" -> (value => value.asInstanceOf[JacketingParams].asJson),
    "LabelingParams" -> (value => value.asInstanceOf[LabelingParams].asJson),
    "LaminatingParams" -> (value => value.asInstanceOf[LaminatingParams].asJson),
    "Layout" -> (value => value.asInstanceOf[Layout].asJson),
    "LayoutElementProductionParams" -> (value => value.asInstanceOf[LayoutElementProductionParams].asJson),
    "LayoutShift" -> (value => value.asInstanceOf[LayoutShift].asJson),
    "LooseBindingParams" -> (value => value.asInstanceOf[LooseBindingParams].asJson),
    "ManualLaborParams" -> (value => value.asInstanceOf[ManualLaborParams].asJson),
    "Media" -> (value => value.asInstanceOf[Media].asJson),
    "MiscConsumable" -> (value => value.asInstanceOf[MiscConsumable].asJson),
    "NodeInfo" -> (value => value.asInstanceOf[NodeInfo].asJson),
    "PDLCreationParams" -> (value => value.asInstanceOf[PDLCreationParams].asJson),
    "Pallet" -> (value => value.asInstanceOf[Pallet].asJson),
    "PalletizingParams" -> (value => value.asInstanceOf[PalletizingParams].asJson),
    "PerforatingParams" -> (value => value.asInstanceOf[PerforatingParams].asJson),
    "PreflightParams" -> (value => value.asInstanceOf[PreflightParams].asJson),
    "PreflightReport" -> (value => value.asInstanceOf[PreflightReport].asJson),
    "Preview" -> (value => value.asInstanceOf[Preview].asJson),
    "PreviewGenerationParams" -> (value => value.asInstanceOf[PreviewGenerationParams].asJson),
    "PrintCondition" -> (value => value.asInstanceOf[PrintCondition].asJson),
    "QualityControlParams" -> (value => value.asInstanceOf[QualityControlParams].asJson),
    "QualityControlResult" -> (value => value.asInstanceOf[QualityControlResult].asJson),
    "RasterReadingParams" -> (value => value.asInstanceOf[RasterReadingParams].asJson),
    "RegisterMark" -> (value => value.asInstanceOf[RegisterMark].asJson),
    "RenderingParams" -> (value => value.asInstanceOf[RenderingParams].asJson),
    "RunList" -> (value => value.asInstanceOf[RunList].asJson),
    "ScreeningParams" -> (value => value.asInstanceOf[ScreeningParams].asJson),
    "SeparationControlParams" -> (value => value.asInstanceOf[SeparationControlParams].asJson),
    "Shape" -> (value => value.asInstanceOf[Shape].asJson),
    "ShapeCuttingParams" -> (value => value.asInstanceOf[ShapeCuttingParams].asJson),
    "ShapeDef" -> (value => value.asInstanceOf[ShapeDef].asJson),
    "ShapeDefProductionParams" -> (value => value.asInstanceOf[ShapeDefProductionParams].asJson),
    "SheetOptimizingParams" -> (value => value.asInstanceOf[SheetOptimizingParams].asJson),
    "SheetOptimizingReport" -> (value => value.asInstanceOf[SheetOptimizingReport].asJson),
    "ShrinkingParams" -> (value => value.asInstanceOf[ShrinkingParams].asJson),
    "SpinePreparationParams" -> (value => value.asInstanceOf[SpinePreparationParams].asJson),
    "SpineTapingParams" -> (value => value.asInstanceOf[SpineTapingParams].asJson),
    "StackingParams" -> (value => value.asInstanceOf[StackingParams].asJson),
    "StitchingParams" -> (value => value.asInstanceOf[StitchingParams].asJson),
    "StrappingParams" -> (value => value.asInstanceOf[StrappingParams].asJson),
    "ThreadSealingParams" -> (value => value.asInstanceOf[ThreadSealingParams].asJson),
    "ThreadSewingParams" -> (value => value.asInstanceOf[ThreadSewingParams].asJson),
    "Tool" -> (value => value.asInstanceOf[Tool].asJson),
    "TransferCurve" -> (value => value.asInstanceOf[TransferCurve].asJson),
    "TrappingParams" -> (value => value.asInstanceOf[TrappingParams].asJson),
    "TrimmingParams" -> (value => value.asInstanceOf[TrimmingParams].asJson),
    "UsageCounter" -> (value => value.asInstanceOf[UsageCounter].asJson),
    "VarnishingParams" -> (value => value.asInstanceOf[VarnishingParams].asJson),
    "VerificationParams" -> (value => value.asInstanceOf[VerificationParams].asJson),
    "VerificationResult" -> (value => value.asInstanceOf[VerificationResult].asJson),
    "WebInlineFinishingParams" -> (value => value.asInstanceOf[WebInlineFinishingParams].asJson),
    "WindingParams" -> (value => value.asInstanceOf[WindingParams].asJson),
    "WrappingParams" -> (value => value.asInstanceOf[WrappingParams].asJson),
  )

  val resourceDecoders: Map[String, Json => Decoder.Result[SpecificResource]] = Map(
    "ApprovalDetails" -> (json => summon[Decoder[ApprovalDetails]].decodeJson(json)),
    "ApprovalParams" -> (json => summon[Decoder[ApprovalParams]].decodeJson(json)),
    "Assembly" -> (json => summon[Decoder[Assembly]].decodeJson(json)),
    "BarcodeCompParams" -> (json => summon[Decoder[BarcodeCompParams]].decodeJson(json)),
    "BarcodeReproParams" -> (json => summon[Decoder[BarcodeReproParams]].decodeJson(json)),
    "BendingParams" -> (json => summon[Decoder[BendingParams]].decodeJson(json)),
    "BinderySignature" -> (json => summon[Decoder[BinderySignature]].decodeJson(json)),
    "BlockPreparationParams" -> (json => summon[Decoder[BlockPreparationParams]].decodeJson(json)),
    "BoxFoldingParams" -> (json => summon[Decoder[BoxFoldingParams]].decodeJson(json)),
    "BoxPackingParams" -> (json => summon[Decoder[BoxPackingParams]].decodeJson(json)),
    "Bundle" -> (json => summon[Decoder[Bundle]].decodeJson(json)),
    "BundlingParams" -> (json => summon[Decoder[BundlingParams]].decodeJson(json)),
    "CaseMakingParams" -> (json => summon[Decoder[CaseMakingParams]].decodeJson(json)),
    "CasingInParams" -> (json => summon[Decoder[CasingInParams]].decodeJson(json)),
    "Color" -> (json => summon[Decoder[Color]].decodeJson(json)),
    "ColorCorrectionParams" -> (json => summon[Decoder[ColorCorrectionParams]].decodeJson(json)),
    "ColorSpaceConversionParams" -> (json => summon[Decoder[ColorSpaceConversionParams]].decodeJson(json)),
    "ColorantControl" -> (json => summon[Decoder[ColorantControl]].decodeJson(json)),
    "Component" -> (json => summon[Decoder[Component]].decodeJson(json)),
    "Contact" -> (json => summon[Decoder[Contact]].decodeJson(json)),
    "Content" -> (json => summon[Decoder[Content]].decodeJson(json)),
    "ConventionalPrintingParams" -> (json => summon[Decoder[ConventionalPrintingParams]].decodeJson(json)),
    "CoverApplicationParams" -> (json => summon[Decoder[CoverApplicationParams]].decodeJson(json)),
    "CreasingParams" -> (json => summon[Decoder[CreasingParams]].decodeJson(json)),
    "CustomerInfo" -> (json => summon[Decoder[CustomerInfo]].decodeJson(json)),
    "CuttingParams" -> (json => summon[Decoder[CuttingParams]].decodeJson(json)),
    "DeliveryParams" -> (json => summon[Decoder[DeliveryParams]].decodeJson(json)),
    "DevelopingParams" -> (json => summon[Decoder[DevelopingParams]].decodeJson(json)),
    "Device" -> (json => summon[Decoder[Device]].decodeJson(json)),
    "DieLayout" -> (json => summon[Decoder[DieLayout]].decodeJson(json)),
    "DieLayoutProductionParams" -> (json => summon[Decoder[DieLayoutProductionParams]].decodeJson(json)),
    "DigitalPrintingParams" -> (json => summon[Decoder[DigitalPrintingParams]].decodeJson(json)),
    "EmbossingParams" -> (json => summon[Decoder[EmbossingParams]].decodeJson(json)),
    "EndSheetGluingParams" -> (json => summon[Decoder[EndSheetGluingParams]].decodeJson(json)),
    "ExposedMedia" -> (json => summon[Decoder[ExposedMedia]].decodeJson(json)),
    "FeedingParams" -> (json => summon[Decoder[FeedingParams]].decodeJson(json)),
    "FoldingParams" -> (json => summon[Decoder[FoldingParams]].decodeJson(json)),
    "FontPolicy" -> (json => summon[Decoder[FontPolicy]].decodeJson(json)),
    "GluingParams" -> (json => summon[Decoder[GluingParams]].decodeJson(json)),
    "HeadBandApplicationParams" -> (json => summon[Decoder[HeadBandApplicationParams]].decodeJson(json)),
    "HoleMakingParams" -> (json => summon[Decoder[HoleMakingParams]].decodeJson(json)),
    "ImageCompressionParams" -> (json => summon[Decoder[ImageCompressionParams]].decodeJson(json)),
    "ImageEnhancementParams" -> (json => summon[Decoder[ImageEnhancementParams]].decodeJson(json)),
    "ImageSetterParams" -> (json => summon[Decoder[ImageSetterParams]].decodeJson(json)),
    "Ink" -> (json => summon[Decoder[Ink]].decodeJson(json)),
    "InkZoneCalculationParams" -> (json => summon[Decoder[InkZoneCalculationParams]].decodeJson(json)),
    "InkZoneProfile" -> (json => summon[Decoder[InkZoneProfile]].decodeJson(json)),
    "InsertingParams" -> (json => summon[Decoder[InsertingParams]].decodeJson(json)),
    "InterpretingParams" -> (json => summon[Decoder[InterpretingParams]].decodeJson(json)),
    "JacketingParams" -> (json => summon[Decoder[JacketingParams]].decodeJson(json)),
    "LabelingParams" -> (json => summon[Decoder[LabelingParams]].decodeJson(json)),
    "LaminatingParams" -> (json => summon[Decoder[LaminatingParams]].decodeJson(json)),
    "Layout" -> (json => summon[Decoder[Layout]].decodeJson(json)),
    "LayoutElementProductionParams" -> (json => summon[Decoder[LayoutElementProductionParams]].decodeJson(json)),
    "LayoutShift" -> (json => summon[Decoder[LayoutShift]].decodeJson(json)),
    "LooseBindingParams" -> (json => summon[Decoder[LooseBindingParams]].decodeJson(json)),
    "ManualLaborParams" -> (json => summon[Decoder[ManualLaborParams]].decodeJson(json)),
    "Media" -> (json => summon[Decoder[Media]].decodeJson(json)),
    "MiscConsumable" -> (json => summon[Decoder[MiscConsumable]].decodeJson(json)),
    "NodeInfo" -> (json => summon[Decoder[NodeInfo]].decodeJson(json)),
    "PDLCreationParams" -> (json => summon[Decoder[PDLCreationParams]].decodeJson(json)),
    "Pallet" -> (json => summon[Decoder[Pallet]].decodeJson(json)),
    "PalletizingParams" -> (json => summon[Decoder[PalletizingParams]].decodeJson(json)),
    "PerforatingParams" -> (json => summon[Decoder[PerforatingParams]].decodeJson(json)),
    "PreflightParams" -> (json => summon[Decoder[PreflightParams]].decodeJson(json)),
    "PreflightReport" -> (json => summon[Decoder[PreflightReport]].decodeJson(json)),
    "Preview" -> (json => summon[Decoder[Preview]].decodeJson(json)),
    "PreviewGenerationParams" -> (json => summon[Decoder[PreviewGenerationParams]].decodeJson(json)),
    "PrintCondition" -> (json => summon[Decoder[PrintCondition]].decodeJson(json)),
    "QualityControlParams" -> (json => summon[Decoder[QualityControlParams]].decodeJson(json)),
    "QualityControlResult" -> (json => summon[Decoder[QualityControlResult]].decodeJson(json)),
    "RasterReadingParams" -> (json => summon[Decoder[RasterReadingParams]].decodeJson(json)),
    "RegisterMark" -> (json => summon[Decoder[RegisterMark]].decodeJson(json)),
    "RenderingParams" -> (json => summon[Decoder[RenderingParams]].decodeJson(json)),
    "RunList" -> (json => summon[Decoder[RunList]].decodeJson(json)),
    "ScreeningParams" -> (json => summon[Decoder[ScreeningParams]].decodeJson(json)),
    "SeparationControlParams" -> (json => summon[Decoder[SeparationControlParams]].decodeJson(json)),
    "Shape" -> (json => summon[Decoder[Shape]].decodeJson(json)),
    "ShapeCuttingParams" -> (json => summon[Decoder[ShapeCuttingParams]].decodeJson(json)),
    "ShapeDef" -> (json => summon[Decoder[ShapeDef]].decodeJson(json)),
    "ShapeDefProductionParams" -> (json => summon[Decoder[ShapeDefProductionParams]].decodeJson(json)),
    "SheetOptimizingParams" -> (json => summon[Decoder[SheetOptimizingParams]].decodeJson(json)),
    "SheetOptimizingReport" -> (json => summon[Decoder[SheetOptimizingReport]].decodeJson(json)),
    "ShrinkingParams" -> (json => summon[Decoder[ShrinkingParams]].decodeJson(json)),
    "SpinePreparationParams" -> (json => summon[Decoder[SpinePreparationParams]].decodeJson(json)),
    "SpineTapingParams" -> (json => summon[Decoder[SpineTapingParams]].decodeJson(json)),
    "StackingParams" -> (json => summon[Decoder[StackingParams]].decodeJson(json)),
    "StitchingParams" -> (json => summon[Decoder[StitchingParams]].decodeJson(json)),
    "StrappingParams" -> (json => summon[Decoder[StrappingParams]].decodeJson(json)),
    "ThreadSealingParams" -> (json => summon[Decoder[ThreadSealingParams]].decodeJson(json)),
    "ThreadSewingParams" -> (json => summon[Decoder[ThreadSewingParams]].decodeJson(json)),
    "Tool" -> (json => summon[Decoder[Tool]].decodeJson(json)),
    "TransferCurve" -> (json => summon[Decoder[TransferCurve]].decodeJson(json)),
    "TrappingParams" -> (json => summon[Decoder[TrappingParams]].decodeJson(json)),
    "TrimmingParams" -> (json => summon[Decoder[TrimmingParams]].decodeJson(json)),
    "UsageCounter" -> (json => summon[Decoder[UsageCounter]].decodeJson(json)),
    "VarnishingParams" -> (json => summon[Decoder[VarnishingParams]].decodeJson(json)),
    "VerificationParams" -> (json => summon[Decoder[VerificationParams]].decodeJson(json)),
    "VerificationResult" -> (json => summon[Decoder[VerificationResult]].decodeJson(json)),
    "WebInlineFinishingParams" -> (json => summon[Decoder[WebInlineFinishingParams]].decodeJson(json)),
    "WindingParams" -> (json => summon[Decoder[WindingParams]].decodeJson(json)),
    "WrappingParams" -> (json => summon[Decoder[WrappingParams]].decodeJson(json)),
  )

  val intentNames: Set[String] = Set(
    "AssemblingIntent",
    "BindingIntent",
    "ColorIntent",
    "ContentCheckIntent",
    "EmbossingIntent",
    "FoldingIntent",
    "HoleMakingIntent",
    "IntentResource",
    "LaminatingIntent",
    "LayoutIntent",
    "MediaIntent",
    "ProductionIntent",
    "ShapeCuttingIntent",
    "VariableIntent",
  )

  val intentEncoders: Map[String, ProductIntent => Json] = Map(
    "AssemblingIntent" -> (value => value.asInstanceOf[AssemblingIntent].asJson),
    "BindingIntent" -> (value => value.asInstanceOf[BindingIntent].asJson),
    "ColorIntent" -> (value => value.asInstanceOf[ColorIntent].asJson),
    "ContentCheckIntent" -> (value => value.asInstanceOf[ContentCheckIntent].asJson),
    "EmbossingIntent" -> (value => value.asInstanceOf[EmbossingIntent].asJson),
    "FoldingIntent" -> (value => value.asInstanceOf[FoldingIntent].asJson),
    "HoleMakingIntent" -> (value => value.asInstanceOf[HoleMakingIntent].asJson),
    "IntentResource" -> (value => value.asInstanceOf[IntentResource].asJson),
    "LaminatingIntent" -> (value => value.asInstanceOf[LaminatingIntent].asJson),
    "LayoutIntent" -> (value => value.asInstanceOf[LayoutIntent].asJson),
    "MediaIntent" -> (value => value.asInstanceOf[MediaIntent].asJson),
    "ProductionIntent" -> (value => value.asInstanceOf[ProductionIntent].asJson),
    "ShapeCuttingIntent" -> (value => value.asInstanceOf[ShapeCuttingIntent].asJson),
    "VariableIntent" -> (value => value.asInstanceOf[VariableIntent].asJson),
  )

  val intentDecoders: Map[String, Json => Decoder.Result[ProductIntent]] = Map(
    "AssemblingIntent" -> (json => summon[Decoder[AssemblingIntent]].decodeJson(json)),
    "BindingIntent" -> (json => summon[Decoder[BindingIntent]].decodeJson(json)),
    "ColorIntent" -> (json => summon[Decoder[ColorIntent]].decodeJson(json)),
    "ContentCheckIntent" -> (json => summon[Decoder[ContentCheckIntent]].decodeJson(json)),
    "EmbossingIntent" -> (json => summon[Decoder[EmbossingIntent]].decodeJson(json)),
    "FoldingIntent" -> (json => summon[Decoder[FoldingIntent]].decodeJson(json)),
    "HoleMakingIntent" -> (json => summon[Decoder[HoleMakingIntent]].decodeJson(json)),
    "IntentResource" -> (json => summon[Decoder[IntentResource]].decodeJson(json)),
    "LaminatingIntent" -> (json => summon[Decoder[LaminatingIntent]].decodeJson(json)),
    "LayoutIntent" -> (json => summon[Decoder[LayoutIntent]].decodeJson(json)),
    "MediaIntent" -> (json => summon[Decoder[MediaIntent]].decodeJson(json)),
    "ProductionIntent" -> (json => summon[Decoder[ProductionIntent]].decodeJson(json)),
    "ShapeCuttingIntent" -> (json => summon[Decoder[ShapeCuttingIntent]].decodeJson(json)),
    "VariableIntent" -> (json => summon[Decoder[VariableIntent]].decodeJson(json)),
  )

  val messageNames: Set[String] = Set(
    "CommandForceGang",
    "CommandModifyQueueEntry",
    "CommandPipeControl",
    "CommandRequestQueueEntry",
    "CommandResource",
    "CommandResubmitQueueEntry",
    "CommandReturnQueueEntry",
    "CommandShutDown",
    "CommandStopPersistentChannel",
    "CommandSubmitQueueEntry",
    "CommandWakeUp",
    "QueryGangStatus",
    "QueryKnownDevices",
    "QueryKnownMessages",
    "QueryKnownSubscriptions",
    "QueryNotification",
    "QueryQueueStatus",
    "QueryResource",
    "QueryStatus",
    "ResponseForceGang",
    "ResponseGangStatus",
    "ResponseKnownDevices",
    "ResponseKnownMessages",
    "ResponseKnownSubscriptions",
    "ResponseModifyQueueEntry",
    "ResponseNotification",
    "ResponsePipeControl",
    "ResponseQueueStatus",
    "ResponseRequestQueueEntry",
    "ResponseResource",
    "ResponseResubmitQueueEntry",
    "ResponseReturnQueueEntry",
    "ResponseShutDown",
    "ResponseStatus",
    "ResponseStopPersistentChannel",
    "ResponseSubmitQueueEntry",
    "ResponseWakeUp",
    "SignalGangStatus",
    "SignalKnownDevices",
    "SignalKnownSubscriptions",
    "SignalNotification",
    "SignalQueueStatus",
    "SignalResource",
    "SignalStatus",
  )

  val messageEncoders: Map[String, Message => Json] = Map(
    "CommandForceGang" -> (value => value.asInstanceOf[CommandForceGang].asJson),
    "CommandModifyQueueEntry" -> (value => value.asInstanceOf[CommandModifyQueueEntry].asJson),
    "CommandPipeControl" -> (value => value.asInstanceOf[CommandPipeControl].asJson),
    "CommandRequestQueueEntry" -> (value => value.asInstanceOf[CommandRequestQueueEntry].asJson),
    "CommandResource" -> (value => value.asInstanceOf[CommandResource].asJson),
    "CommandResubmitQueueEntry" -> (value => value.asInstanceOf[CommandResubmitQueueEntry].asJson),
    "CommandReturnQueueEntry" -> (value => value.asInstanceOf[CommandReturnQueueEntry].asJson),
    "CommandShutDown" -> (value => value.asInstanceOf[CommandShutDown].asJson),
    "CommandStopPersistentChannel" -> (value => value.asInstanceOf[CommandStopPersistentChannel].asJson),
    "CommandSubmitQueueEntry" -> (value => value.asInstanceOf[CommandSubmitQueueEntry].asJson),
    "CommandWakeUp" -> (value => value.asInstanceOf[CommandWakeUp].asJson),
    "QueryGangStatus" -> (value => value.asInstanceOf[QueryGangStatus].asJson),
    "QueryKnownDevices" -> (value => value.asInstanceOf[QueryKnownDevices].asJson),
    "QueryKnownMessages" -> (value => value.asInstanceOf[QueryKnownMessages].asJson),
    "QueryKnownSubscriptions" -> (value => value.asInstanceOf[QueryKnownSubscriptions].asJson),
    "QueryNotification" -> (value => value.asInstanceOf[QueryNotification].asJson),
    "QueryQueueStatus" -> (value => value.asInstanceOf[QueryQueueStatus].asJson),
    "QueryResource" -> (value => value.asInstanceOf[QueryResource].asJson),
    "QueryStatus" -> (value => value.asInstanceOf[QueryStatus].asJson),
    "ResponseForceGang" -> (value => value.asInstanceOf[ResponseForceGang].asJson),
    "ResponseGangStatus" -> (value => value.asInstanceOf[ResponseGangStatus].asJson),
    "ResponseKnownDevices" -> (value => value.asInstanceOf[ResponseKnownDevices].asJson),
    "ResponseKnownMessages" -> (value => value.asInstanceOf[ResponseKnownMessages].asJson),
    "ResponseKnownSubscriptions" -> (value => value.asInstanceOf[ResponseKnownSubscriptions].asJson),
    "ResponseModifyQueueEntry" -> (value => value.asInstanceOf[ResponseModifyQueueEntry].asJson),
    "ResponseNotification" -> (value => value.asInstanceOf[ResponseNotification].asJson),
    "ResponsePipeControl" -> (value => value.asInstanceOf[ResponsePipeControl].asJson),
    "ResponseQueueStatus" -> (value => value.asInstanceOf[ResponseQueueStatus].asJson),
    "ResponseRequestQueueEntry" -> (value => value.asInstanceOf[ResponseRequestQueueEntry].asJson),
    "ResponseResource" -> (value => value.asInstanceOf[ResponseResource].asJson),
    "ResponseResubmitQueueEntry" -> (value => value.asInstanceOf[ResponseResubmitQueueEntry].asJson),
    "ResponseReturnQueueEntry" -> (value => value.asInstanceOf[ResponseReturnQueueEntry].asJson),
    "ResponseShutDown" -> (value => value.asInstanceOf[ResponseShutDown].asJson),
    "ResponseStatus" -> (value => value.asInstanceOf[ResponseStatus].asJson),
    "ResponseStopPersistentChannel" -> (value => value.asInstanceOf[ResponseStopPersistentChannel].asJson),
    "ResponseSubmitQueueEntry" -> (value => value.asInstanceOf[ResponseSubmitQueueEntry].asJson),
    "ResponseWakeUp" -> (value => value.asInstanceOf[ResponseWakeUp].asJson),
    "SignalGangStatus" -> (value => value.asInstanceOf[SignalGangStatus].asJson),
    "SignalKnownDevices" -> (value => value.asInstanceOf[SignalKnownDevices].asJson),
    "SignalKnownSubscriptions" -> (value => value.asInstanceOf[SignalKnownSubscriptions].asJson),
    "SignalNotification" -> (value => value.asInstanceOf[SignalNotification].asJson),
    "SignalQueueStatus" -> (value => value.asInstanceOf[SignalQueueStatus].asJson),
    "SignalResource" -> (value => value.asInstanceOf[SignalResource].asJson),
    "SignalStatus" -> (value => value.asInstanceOf[SignalStatus].asJson),
  )

  val messageDecoders: Map[String, Json => Decoder.Result[Message]] = Map(
    "CommandForceGang" -> (json => summon[Decoder[CommandForceGang]].decodeJson(json)),
    "CommandModifyQueueEntry" -> (json => summon[Decoder[CommandModifyQueueEntry]].decodeJson(json)),
    "CommandPipeControl" -> (json => summon[Decoder[CommandPipeControl]].decodeJson(json)),
    "CommandRequestQueueEntry" -> (json => summon[Decoder[CommandRequestQueueEntry]].decodeJson(json)),
    "CommandResource" -> (json => summon[Decoder[CommandResource]].decodeJson(json)),
    "CommandResubmitQueueEntry" -> (json => summon[Decoder[CommandResubmitQueueEntry]].decodeJson(json)),
    "CommandReturnQueueEntry" -> (json => summon[Decoder[CommandReturnQueueEntry]].decodeJson(json)),
    "CommandShutDown" -> (json => summon[Decoder[CommandShutDown]].decodeJson(json)),
    "CommandStopPersistentChannel" -> (json => summon[Decoder[CommandStopPersistentChannel]].decodeJson(json)),
    "CommandSubmitQueueEntry" -> (json => summon[Decoder[CommandSubmitQueueEntry]].decodeJson(json)),
    "CommandWakeUp" -> (json => summon[Decoder[CommandWakeUp]].decodeJson(json)),
    "QueryGangStatus" -> (json => summon[Decoder[QueryGangStatus]].decodeJson(json)),
    "QueryKnownDevices" -> (json => summon[Decoder[QueryKnownDevices]].decodeJson(json)),
    "QueryKnownMessages" -> (json => summon[Decoder[QueryKnownMessages]].decodeJson(json)),
    "QueryKnownSubscriptions" -> (json => summon[Decoder[QueryKnownSubscriptions]].decodeJson(json)),
    "QueryNotification" -> (json => summon[Decoder[QueryNotification]].decodeJson(json)),
    "QueryQueueStatus" -> (json => summon[Decoder[QueryQueueStatus]].decodeJson(json)),
    "QueryResource" -> (json => summon[Decoder[QueryResource]].decodeJson(json)),
    "QueryStatus" -> (json => summon[Decoder[QueryStatus]].decodeJson(json)),
    "ResponseForceGang" -> (json => summon[Decoder[ResponseForceGang]].decodeJson(json)),
    "ResponseGangStatus" -> (json => summon[Decoder[ResponseGangStatus]].decodeJson(json)),
    "ResponseKnownDevices" -> (json => summon[Decoder[ResponseKnownDevices]].decodeJson(json)),
    "ResponseKnownMessages" -> (json => summon[Decoder[ResponseKnownMessages]].decodeJson(json)),
    "ResponseKnownSubscriptions" -> (json => summon[Decoder[ResponseKnownSubscriptions]].decodeJson(json)),
    "ResponseModifyQueueEntry" -> (json => summon[Decoder[ResponseModifyQueueEntry]].decodeJson(json)),
    "ResponseNotification" -> (json => summon[Decoder[ResponseNotification]].decodeJson(json)),
    "ResponsePipeControl" -> (json => summon[Decoder[ResponsePipeControl]].decodeJson(json)),
    "ResponseQueueStatus" -> (json => summon[Decoder[ResponseQueueStatus]].decodeJson(json)),
    "ResponseRequestQueueEntry" -> (json => summon[Decoder[ResponseRequestQueueEntry]].decodeJson(json)),
    "ResponseResource" -> (json => summon[Decoder[ResponseResource]].decodeJson(json)),
    "ResponseResubmitQueueEntry" -> (json => summon[Decoder[ResponseResubmitQueueEntry]].decodeJson(json)),
    "ResponseReturnQueueEntry" -> (json => summon[Decoder[ResponseReturnQueueEntry]].decodeJson(json)),
    "ResponseShutDown" -> (json => summon[Decoder[ResponseShutDown]].decodeJson(json)),
    "ResponseStatus" -> (json => summon[Decoder[ResponseStatus]].decodeJson(json)),
    "ResponseStopPersistentChannel" -> (json => summon[Decoder[ResponseStopPersistentChannel]].decodeJson(json)),
    "ResponseSubmitQueueEntry" -> (json => summon[Decoder[ResponseSubmitQueueEntry]].decodeJson(json)),
    "ResponseWakeUp" -> (json => summon[Decoder[ResponseWakeUp]].decodeJson(json)),
    "SignalGangStatus" -> (json => summon[Decoder[SignalGangStatus]].decodeJson(json)),
    "SignalKnownDevices" -> (json => summon[Decoder[SignalKnownDevices]].decodeJson(json)),
    "SignalKnownSubscriptions" -> (json => summon[Decoder[SignalKnownSubscriptions]].decodeJson(json)),
    "SignalNotification" -> (json => summon[Decoder[SignalNotification]].decodeJson(json)),
    "SignalQueueStatus" -> (json => summon[Decoder[SignalQueueStatus]].decodeJson(json)),
    "SignalResource" -> (json => summon[Decoder[SignalResource]].decodeJson(json)),
    "SignalStatus" -> (json => summon[Decoder[SignalStatus]].decodeJson(json)),
  )

  /** The dispatch name of a specific resource: the normative element name equals the runtime class name. */
  def resourceName(resource: SpecificResource): String = resource.getClass.getSimpleName

  /** The dispatch name of a product intent. */
  def intentName(intent: ProductIntent): String = intent.getClass.getSimpleName

  /** The dispatch name of a message. */
  def messageName(message: Message): String = message.getClass.getSimpleName

  def encodeSpecificResource(resource: SpecificResource): Json =
    resourceEncoders.get(resourceName(resource)) match
      case Some(encode) => encode(resource)
      case None => throw new UnsupportedOperationException(
          s"no JSON codec for resource ${resourceName(resource)}",
        )

  def decodeSpecificResource(name: String, json: Json): Decoder.Result[SpecificResource] =
    resourceDecoders.get(name) match
      case Some(decode) => decode(json)
      case None => JsonHelpers.fail(json.hcursor, s"resource '$name' is not covered by the JSON codec")

  def encodeProductIntent(intent: ProductIntent): Json =
    intentEncoders.get(intentName(intent)) match
      case Some(encode) => encode(intent)
      case None => throw new UnsupportedOperationException(
          s"no JSON codec for intent ${intentName(intent)}",
        )

  def decodeProductIntent(name: String, json: Json): Decoder.Result[ProductIntent] =
    intentDecoders.get(name) match
      case Some(decode) => decode(json)
      case None => JsonHelpers.fail(json.hcursor, s"intent '$name' is not covered by the JSON codec")

  def encodeMessage(message: Message): Json =
    messageEncoders.get(messageName(message)) match
      case Some(encode) => encode(message)
      case None => throw new UnsupportedOperationException(
          s"no JSON codec for message ${messageName(message)}",
        )

  def decodeMessage(name: String, json: Json): Decoder.Result[Message] =
    messageDecoders.get(name) match
      case Some(decode) => decode(json)
      case None => JsonHelpers.fail(json.hcursor, s"message '$name' is not covered by the JSON codec")
end JsonRegistry
