package xjdf4s
package model

import xjdf4s.prim.*
import cats.{Eval, Functor, Show}
import cats.data.{Chain, NonEmptyChain, ValidatedNec}
import cats.kernel.Eq
import cats.syntax.all.*

/** The `Product` element (Table 3.11): an individual product or product part of
 *  the bill of materials. `@Amount` for a part specifies the number of copies of
 *  the part needed to create *one* parent product (§3.3.1.1).
 */
final case class Product(
    amount: Option[Long] = None,
    maxAmount: Option[Long] = None,
    minAmount: Option[Long] = None,
    commentUrl: Option[Url] = None,
    descriptiveName: Option[XjdfString] = None,
    externalId: Option[NmToken] = None,
    id: Option[Id] = None,
    isRoot: Boolean = true,
    partVersion: Option[NmToken] = None,
    productType: Option[NmToken] = None,
    productTypeDetails: Option[XjdfString] = None,
    intents: Chain[Intent] = Chain.empty,
    comments: Chain[Comment] = Chain.empty,
    generalIds: Chain[GeneralID] = Chain.empty
):

  /** All IDREFs this product points at (e.g. `BindingIntent/@ChildRefs`). */
  def references: Chain[IdRef] =
    intents.flatMap(_.references)

  /** True when all amounts are non-negative. */
  def hasLawfulAmounts: Boolean =
    List(amount, maxAmount, minAmount).flatten.forall(_ >= 0L)
end Product

object Product:

  /** §3.3.1.1: product amounts SHALL be non-negative. Explicitly invoked
   *  from `TicketValidator.checkLocalLaws`.
   */
  val amountsLaw: DomainRule[Product] =
    (value: Product, at: XPath) =>
      val bad = List(
        value.amount.map(a => "@Amount" -> a),
        value.maxAmount.map(a => "@MaxAmount" -> a),
        value.minAmount.map(a => "@MinAmount" -> a)
      ).flatten.filter(_._2 < 0L)
      Chain.fromSeq(bad).map { case (name, a) =>
        Issue.errorC(
          IssueCode.LocalLawViolation,
          at,
          s"Product $name=$a SHALL be non-negative (§3.3.1.1)"
        )
      }

  given Show[Product] =
    Show.show { p =>
      val name = p.productType.map(_.value).orElse(p.descriptiveName.map(_.value)).getOrElse("?")
      val amount = p.amount.map(a => s"×$a").getOrElse("")
      s"Product($name$amount${if p.isRoot then ", root" else ", part"})"
    }

  given Eq[Product] = Eq.fromUniversalEquals

end Product

/** `ProductList` (Table 3.10): a non-empty list of products — the bill of
 *  materials from the print buyer's point of view.
 */
final case class ProductList(products: NonEmptyChain[Product]):

  /** The root products (`@IsRoot="true"`); more than one implies a Gang job. */
  def roots: Chain[Product] =
    Chain.fromSeq(products.toChain.toList.filter(_.isRoot))

  def parts: Chain[Product] =
    Chain.fromSeq(products.toChain.toList.filterNot(_.isRoot))

  /** Looks a product up by its document-scoped `@ID`. */
  def byId(id: Id): Option[Product] =
    products.toChain.toList.find(_.id.contains(id))

  /** Resolves an IDREF against this product list. */
  def resolve(ref: IdRef): Option[Product] =
    byId(Id.unsafe(ref.value))

  /** All document-scoped IDs declared by the products. */
  def declaredIds: Chain[Id] =
    Chain.fromSeq(products.toChain.toList.flatMap(_.id))

  /** All IDREFs used by the products (e.g. binding child references). */
  def references: Chain[IdRef] =
    products.toChain.flatMap(_.references)
end ProductList

object ProductList:

  def of(head: Product, tail: Product*): ProductList =
    ProductList(NonEmptyChain(head, tail*))

  given Show[ProductList] =
    Show.show(pl => pl.products.toChain.toList.map(Show[Product].show).mkString("ProductList(", ", ", ")"))

  given Eq[ProductList] = Eq.fromUniversalEquals

end ProductList

/** The pattern functor of a bill of materials: a product node is either a leaf
 *  or a node with child sub-trees. This is the *F* of the initial-algebra
 *  construction over products (`Fix[ProductTree]`), and a catamorphism folds any
 *  `ProductTree[A] => A` algebra over it.
 */
enum ProductTree[+A]:
  case Leaf(product: Product)
  case Node(product: Product, children: Chain[A])

object ProductTree:

  given Functor[ProductTree] with
    def map[A, B](fa: ProductTree[A])(f: A => B): ProductTree[B] =
      fa match
        case Leaf(p) => Leaf(p)
        case Node(p, kids) => Node(p, kids.map(f))

end ProductTree

/** `Fix[F]`: the least fixed point of a functor — the recursive type of trees
 *  generated by `ProductTree`.
 */
final case class Fix[F[_]](unfix: F[Fix[F]])

/** Builds and folds the bill of materials.
 *
 *  The BOM of a ProductList is a *graph* (products reference each other by ID),
 *  and the `Fix[ProductTree]` tree exists exactly when those references form an
 *  acyclic forest rooted at `@IsRoot="true"` products. Cycle/unresolved-ref
 *  detection makes `fromProductList` a *monadic* unfold.
 *
 *  Stack safety (N-27 / M1.4-7): both `toTree` (the unfold) and `cataEval`
 *  (the fold) use `Eval.defer` to trampoline recursive calls, making deep
 *  BOMs (≥10 000 depth) safe against `StackOverflowError`.
 */
object Bom:

  /** The recursive node type of a product BOM. */
  type Tree = Fix[ProductTree]

  // ------------------------------------------------------------------
  // Stack-safe tree unfold (N-27)
  // ------------------------------------------------------------------

  /** Stack-safe variant of `toTree` using `Eval.defer` for each recursive
   *  descent into a child product. A chain of 10 000 `@ChildRefs` will not
   *  overflow the JVM stack.
   */
  private def toTreeEval(
      product: Product,
      byId: Map[String, Product],
      seen: Set[String]
  ): Eval[Either[Issue, Fix[ProductTree]]] =
    val currentId = product.id.map(_.value)
    currentId match
      case Some(id) if seen.contains(id) =>
        Eval.now(Left(Issue.errorC(
          IssueCode.BomCycle,
          XPath("/XJDF/ProductList"),
          s"Cycle in product structure at ID '$id'"
        )))
      case _ =>
        val nextSeen = currentId.fold(seen)(seen + _)
        product.references.toList.distinct match
          case Nil =>
            Eval.now(Right(Fix(ProductTree.Leaf(product))))
          case refs =>
            Eval.defer(processRefs(refs, byId, nextSeen, Chain.empty))
              .map(_.map(cs => Fix(ProductTree.Node(product, cs))))

  /** Processes child references one by one with `Eval.defer` between each
   *  recursive call, keeping the stack bounded.
   */
  private def processRefs(
      refs: List[IdRef],
      byId: Map[String, Product],
      nextSeen: Set[String],
      acc: Chain[Fix[ProductTree]]
  ): Eval[Either[Issue, Chain[Fix[ProductTree]]]] =
    refs match
      case Nil =>
        Eval.now(Right(acc))
      case ref :: rest =>
        byId.get(ref.value) match
          case None =>
            Eval.now(Left(Issue.errorC(
              IssueCode.BomUnresolvedChildRef,
              XPath("/XJDF/ProductList"),
              s"Unresolved ChildRef '${ref.value}'"
            )))
          case Some(child) =>
            Eval.defer(toTreeEval(child, byId, nextSeen)).flatMap {
              case Left(issue) => Eval.now(Left(issue))
              case Right(kid) => processRefs(rest, byId, nextSeen, acc :+ kid)
            }

  /** Wrapper that evaluates the `Eval` trampoline. */
  private def toTree(
      product: Product,
      byId: Map[String, Product],
      seen: Set[String]
  ): Either[Issue, Fix[ProductTree]] =
    toTreeEval(product, byId, seen).value

  /** Unfolds a ProductList into a forest of product trees. Fails on unresolved
   *  references and cycles. Roots are ordered as in the ProductList.
   */
  def fromProductList(pl: ProductList): Either[Issue, NonEmptyChain[Fix[ProductTree]]] =
    val byId: Map[String, Product] =
      pl.products.toChain.toList.flatMap(p => p.id.map(id => id.value -> p)).toMap
    val roots = pl.roots
    if roots.isEmpty then
      Left(Issue.errorC(
        IssueCode.BomNoRoot,
        XPath("/XJDF/ProductList"),
        "A ProductList SHALL contain at least one root product"
      ))
    else
      val trees = roots.foldLeft(Right(Chain.empty[Fix[ProductTree]]): Either[Issue, Chain[Fix[ProductTree]]]) {
        case (acc, p) =>
          for
            ts <- acc
            t  <- toTree(p, byId, Set.empty)
          yield ts :+ t
      }
      trees.flatMap(ts =>
        NonEmptyChain.fromChain(ts).toRight(
          Issue.errorC(IssueCode.BomNoRoot, XPath("/XJDF/ProductList"), "Empty product list"))
      )

  // ------------------------------------------------------------------
  // Stack-safe catamorphism (N-27)
  // ------------------------------------------------------------------

  /** A stack-safe catamorphism using `Eval` for trampolined recursion.
   *  Each recursive child descent is wrapped with `Eval.defer`, bounding
   *  the JVM call stack to a constant depth regardless of tree depth.
   */
  def cataEval[A](algebra: ProductTree[A] => Eval[A])(tree: Fix[ProductTree]): Eval[A] =
    tree.unfix match
      case ProductTree.Leaf(p) =>
        algebra(ProductTree.Leaf(p))
      case ProductTree.Node(p, kids) =>
        kids.traverse(k => Eval.defer(cataEval(algebra)(k)))
          .flatMap(cs => algebra(ProductTree.Node(p, cs)))

  /** A catamorphism: folds an `ProductTree[A] => A` algebra over the whole tree.
   *  Delegates to `cataEval` — its stack safety depends on `Eval`'s trampoline,
   *  which is guaranteed for cats `Eval` (always-eager loop). If unbounded
   *  recursion is observed, use `cataEval` directly.
   */
  def cata[A](algebra: ProductTree[A] => A)(tree: Fix[ProductTree]): A =
    cataEval(a => Eval.now(algebra(a)))(tree).value

  // ------------------------------------------------------------------
  // Derived folds
  // ------------------------------------------------------------------

  /** Amount validation as a catamorphism: the algebra's carrier is
   *  `ValidatedNec[Issue, Unit]` — the applicative functor of accumulated
   *  errors — so the fold reports every unlawful amount in the BOM at once.
   */
  def validateAmounts(tree: Fix[ProductTree]): ValidatedNec[Issue, Unit] =
    cata[ValidatedNec[Issue, Unit]] {
      case ProductTree.Leaf(p) => checkAmounts(p)
      case ProductTree.Node(p, kids) => checkAmounts(p) |+| kids.combineAll
    }(tree)

  private def checkAmounts(p: Product): ValidatedNec[Issue, Unit] =
    val bad = List(p.amount, p.maxAmount, p.minAmount).flatten.filter(_ < 0L)
    if bad.isEmpty then ().validNec
    else
      Issue.errorC(
        IssueCode.LocalLawViolation,
        XPath("/XJDF/ProductList"),
        s"Negative product amount in $p"
      ).invalidNec

  /** The total number of copies of every product in the BOM, following
   *  §3.3.1.1: a parent amount multiplies the per-parent amounts of its parts.
   *  A top-down fold (anamorphic stream of multipliers).
   */
  def totalCopies(tree: Fix[ProductTree]): List[(Product, Long)] =
    def go(multiplier: Long, t: Fix[ProductTree]): List[(Product, Long)] =
      t.unfix match
        case ProductTree.Leaf(p) =>
          List(p -> (multiplier * p.amount.getOrElse(1L)))
        case ProductTree.Node(p, kids) =>
          val total = multiplier * p.amount.getOrElse(1L)
          (p -> total) :: kids.toList.flatMap(go(total, _))
    go(1L, tree)
end Bom
