package xjdf4s.codec.xml

import xjdf4s.codec.xml.domain.Registry

/** Completeness of the generated dispatch registries: every standard resource, product intent and XJMF message of
 *  the model union types must have a codec entry. The expected sets are generated from the model union lists.
 */
object RegistryCoverageChecks:
  private val expectedResources: Set[String] = Set(
    "ApprovalDetails",
    "ApprovalParams",
    "Assembly",
    "BarcodeCompParams",
    "BarcodeReproParams",
    "BendingParams",
    "BinderySignature",
    "BlockPreparationParams",
    "BoxFoldingParams",
    "BoxPackingParams",
    "Bundle",
    "BundlingParams",
    "CaseMakingParams",
    "CasingInParams",
    "Color",
    "ColorCorrectionParams",
    "ColorSpaceConversionParams",
    "ColorantControl",
    "Component",
    "Contact",
    "Content",
    "ConventionalPrintingParams",
    "CoverApplicationParams",
    "CreasingParams",
    "CustomerInfo",
    "CuttingParams",
    "DeliveryParams",
    "DevelopingParams",
    "Device",
    "DieLayout",
    "DieLayoutProductionParams",
    "DigitalPrintingParams",
    "EmbossingParams",
    "EndSheetGluingParams",
    "ExposedMedia",
    "FeedingParams",
    "FoldingParams",
    "FontPolicy",
    "GluingParams",
    "HeadBandApplicationParams",
    "HoleMakingParams",
    "ImageCompressionParams",
    "ImageEnhancementParams",
    "ImageSetterParams",
    "Ink",
    "InkZoneCalculationParams",
    "InkZoneProfile",
    "InsertingParams",
    "InterpretingParams",
    "JacketingParams",
    "LabelingParams",
    "LaminatingParams",
    "Layout",
    "LayoutElementProductionParams",
    "LayoutShift",
    "LooseBindingParams",
    "ManualLaborParams",
    "Media",
    "MiscConsumable",
    "NodeInfo",
    "PDLCreationParams",
    "Pallet",
    "PalletizingParams",
    "PerforatingParams",
    "PreflightParams",
    "PreflightReport",
    "Preview",
    "PreviewGenerationParams",
    "PrintCondition",
    "QualityControlParams",
    "QualityControlResult",
    "RasterReadingParams",
    "RegisterMark",
    "RenderingParams",
    "RunList",
    "ScreeningParams",
    "SeparationControlParams",
    "Shape",
    "ShapeCuttingParams",
    "ShapeDef",
    "ShapeDefProductionParams",
    "SheetOptimizingParams",
    "SheetOptimizingReport",
    "ShrinkingParams",
    "SpinePreparationParams",
    "SpineTapingParams",
    "StackingParams",
    "StitchingParams",
    "StrappingParams",
    "ThreadSealingParams",
    "ThreadSewingParams",
    "Tool",
    "TransferCurve",
    "TrappingParams",
    "TrimmingParams",
    "UsageCounter",
    "VarnishingParams",
    "VerificationParams",
    "VerificationResult",
    "WebInlineFinishingParams",
    "WindingParams",
    "WrappingParams",
  )

  private val expectedIntents: Set[String] = Set(
    "AssemblingIntent",
    "BindingIntent",
    "ColorIntent",
    "ContentCheckIntent",
    "EmbossingIntent",
    "FoldingIntent",
    "HoleMakingIntent",
    "IntentResource",
    "LaminatingIntent",
    "LayoutIntent",
    "MediaIntent",
    "ProductionIntent",
    "ShapeCuttingIntent",
    "VariableIntent",
  )

  private val expectedMessages: Set[String] = Set(
    "CommandForceGang",
    "CommandModifyQueueEntry",
    "CommandPipeControl",
    "CommandRequestQueueEntry",
    "CommandResource",
    "CommandResubmitQueueEntry",
    "CommandReturnQueueEntry",
    "CommandShutDown",
    "CommandStopPersistentChannel",
    "CommandSubmitQueueEntry",
    "CommandWakeUp",
    "QueryGangStatus",
    "QueryKnownDevices",
    "QueryKnownMessages",
    "QueryKnownSubscriptions",
    "QueryNotification",
    "QueryQueueStatus",
    "QueryResource",
    "QueryStatus",
    "ResponseForceGang",
    "ResponseGangStatus",
    "ResponseKnownDevices",
    "ResponseKnownMessages",
    "ResponseKnownSubscriptions",
    "ResponseModifyQueueEntry",
    "ResponseNotification",
    "ResponsePipeControl",
    "ResponseQueueStatus",
    "ResponseRequestQueueEntry",
    "ResponseResource",
    "ResponseResubmitQueueEntry",
    "ResponseReturnQueueEntry",
    "ResponseShutDown",
    "ResponseStatus",
    "ResponseStopPersistentChannel",
    "ResponseSubmitQueueEntry",
    "ResponseWakeUp",
    "SignalGangStatus",
    "SignalKnownDevices",
    "SignalKnownSubscriptions",
    "SignalNotification",
    "SignalQueueStatus",
    "SignalResource",
    "SignalStatus",
  )

  val resourceCoverage: Unit =
    assert(Registry.resourceNames == expectedResources, Registry.resourceNames.diff(expectedResources))

  val intentCoverage: Unit =
    assert(Registry.intentNames == expectedIntents, Registry.intentNames.diff(expectedIntents))

  val messageCoverage: Unit =
    assert(Registry.messageNames == expectedMessages, Registry.messageNames.diff(expectedMessages))
end RegistryCoverageChecks
