package xjdf4s.model

/** Discovered munit suite that forces all eager checks of the model module (MD-08). */
class ModelChecksSuite extends munit.FunSuite:
  test("all model checks pass"):
    val results: Vector[Unit] = Vector(
      AdditionalResourceChecks.recursiveAssembly,
      AdditionalResourceChecks.recursiveBundle,
      AdditionalResourceChecks.constrainedCommonFolds,
      AuditChecks.auditChoice,
      AuditChecks.boundedCardinality,
      ContentAndDieLayoutChecks.positionedContent,
      ContentAndDieLayoutChecks.dieStations,
      FileSpecChecks.exclusiveLocations,
      FileSpecChecks.typedDisposition,
      FoundationalResourceChecks.foundationalUnion,
      FoundationalResourceChecks.countryCodeValidation,
      GangAndSignatureChecks.requiredGangElements,
      GangAndSignatureChecks.cellConditions,
      GeneralResourceChecks.requiredApprovalPeople,
      GeneralResourceChecks.verificationFileRoles,
      GeneralResourceChecks.pressResources,
      ImagingResourceChecks.imageCompressionCardinality,
      ImagingResourceChecks.colorConversionOperation,
      ImagingResourceChecks.typedTiffTagValue,
      InterpretingAndDieChecks.interpretingPolicy,
      InterpretingAndDieChecks.productionCardinalities,
      LayoutResourceChecks.placedObjectChoice,
      LayoutResourceChecks.conditionalSheet,
      MediaResourceChecks.orderedMediaLayers,
      MediaResourceChecks.deviceCardinality,
      MediaResourceChecks.deviceNSeparations,
      NormativeResourceChecks.omittedHierarchyMember,
      NormativeResourceChecks.normativeReport,
      NormativeResourceChecks.xjdf22JobPhaseAmount,
      PdlCreationChecks.pdfOutput,
      PdlCreationChecks.postScriptOutput,
      PostpressResourceChecks.requiredChildren,
      PostpressResourceChecks.requiredAttributes,
      PrepressResourceChecks.requiredOperationCardinality,
      PrepressResourceChecks.requiredShiftPoints,
      ProcessResourceChecks.cuttingInstructions,
      ProcessResourceChecks.requiredScreenSelectors,
      ProcessResourceChecks.requiredMarkFields,
      ProductIntentChecks.assemblingIsStandard,
      ProductIntentChecks.bindingDetailsMatchType,
      ProductIntentChecks.semanticCardinalities,
      QualityControlChecks.boundedSeverity,
      QualityControlChecks.defectKindsAreNonEmpty,
      QualityControlChecks.namedMasterFiles,
      RemainingPostpressChecks.bindingDetailsFollowType,
      RemainingPostpressChecks.boxFoldingOrderedActions,
      RemainingPostpressChecks.exclusiveCollatingPlacement,
      SmallProductionResourceChecks.nestedDevice,
      SmallProductionResourceChecks.inlineFinishing,
      StackingResourceChecks.nestedStripMarks,
      ConsolidatedAuditChecks.closedVocabularies,
      ConsolidatedAuditChecks.namedColorVocabulary,
      ConsolidatedAuditChecks.boundedColorProducts,
      ConsolidatedAuditChecks.evenLengthLists,
      ConsolidatedAuditChecks.foldCatalogPattern,
      ConsolidatedAuditChecks.partIntegerRanges,
      ConsolidatedAuditChecks.resourceXorPlacementAndTiming,
      ConsolidatedAuditChecks.mediaIntentBackIsoCompanion,
      ConsolidatedAuditChecks.xjdfDocumentValidation,
      ConsolidatedAuditChecks.toolAndPatch22Fields,
      ConsolidatedAuditChecks.priorityCarriers,
      ConsolidatedAuditChecks.conditionPartContextIsList,
      ConsolidatedAuditChecks.integerProcessIndices,
    )
    assert(results.size == 63)
end ModelChecksSuite
