package xjdf4s.codec.json

/** Discovered munit suite that forces all eager checks of the codec-json module. */
class JsonChecksSuite extends munit.FunSuite:
  test("all json checks pass") {
    val results: Vector[Unit] = Vector(
      JsonChecks.scalars,
      JsonChecks.mediaWithLayers,
      JsonChecks.resourceTree,
      JsonChecks.transferFunctionPoints,
      JsonChecks.commentTextMember,
      JsonChecks.auditPool,
      JsonChecks.messages,
      JsonExceptionChecks.rootSchemaMember,
      JsonExceptionChecks.xjmfExactlyOneMessage,
      JsonExceptionChecks.mediaLayersInlineName,
      NormativeJsonFixtureChecks.example31Root,
      NormativeJsonFixtureChecks.example85MediaLayers,
      NormativeJsonFixtureChecks.example911AuditPool,
      NormativeJsonFixtureChecks.example71Xjmf,
      CrossCodecPropertyChecks.xjdfDocuments,
      CrossCodecPropertyChecks.xjmfMessages,
      JsonDerivedChecks.fileSpec,
      JsonDerivedChecks.deliveryParams,
      JsonDerivedChecks.tiffFormatParams,
      JsonDerivedChecks.placedObject,
      JsonDerivedChecks.contact,
      JsonDerivedChecks.bundleItem,
      JsonDerivedChecks.assemblySection,
      JsonDerivedChecks.message,
      JsonDerivedChecks.intent,
      JsonDerivedChecks.productWithIntent,
      JsonDerivedChecks.nodeInfoStatus,
      JsonDerivedChecks.layoutExpansionBox,
      JsonDerivedChecks.stickOn,
      JsonDerivedChecks.collatingItem,
      JsonDerivedChecks.looseBindingParams,
      JsonDerivedChecks.assembly,
      JsonDerivedChecks.bindingIntent,
      JsonDerivedChecks.colorIntent,
      JsonDerivedChecks.modifyQueueEntryParams,
      JsonDerivedChecks.queueSubmissionParams,
      JsonDerivedChecks.productListRoot,
      JsonDerivedChecks.dependentResourceSet,
      JsonDerivedChecks.foreignResource,
      JsonDerivedChecks.foreignIntent,
      JsonDerivedChecks.foreignExtensions,
      JsonDerivedChecks.registryCoverage,
    )
    assert(results.size == 42)
  }
