package xjdf4s.dsl

import xjdf4s.core.*
import xjdf4s.model.*

object DocDslChecks:
  private val jobId = Nmtoken.from("job-1").toOption.get
  private val process = Nmtoken.from("Product").toOption.get
  private val mediaName = Nmtoken.from("Media").toOption.get

  private def seed: XJDF = XJDF(jobId, NonEmptyVector.one(process))

  val buildInterpreter: Unit =
    val program =
      for
        _ <- DocDsl.version(Version.V2_2)
        _ <- DocDsl.comment("generated by test")
        _ <- DocDsl.resourceSet(mediaName, ResourceUsage.Input)(Resource())
      yield ()
    val document = DocInterpreters.run(program, seed)
    assert(document.version.contains(Version.V2_2))
    assert(document.comments.size == 1)
    assert(document.resourceSets.size == 1)
    assert(document.validateAll.isValid)

  val traceInterpreter: Unit =
    val program =
      for
        _ <- DocDsl.version(Version.V2_2)
        _ <- DocDsl.resourceSet(mediaName, ResourceUsage.Input)(Resource())
      yield ()
    assert(
      DocInterpreters.trace(program).toList ==
        List("set version 2.2", "add resource set Media"),
    )

  val dryRunValidation: Unit =
    val invalid = Resource(orientation = Some(Orientation.Rotate90), transformation = Some(Matrix.identity))
    assert(DocInterpreters.dryRun(DocDsl.resourceSet(mediaName, ResourceUsage.Input)(invalid)).isLeft)
    assert(DocInterpreters.dryRun(DocDsl.resourceSet(mediaName, ResourceUsage.Input)(Resource())).isRight)

  val oneProgramThreeInterpreters: Unit =
    val program =
      for
        _ <- DocDsl.version(Version.V2_2)
        _ <- DocDsl.resourceSet(mediaName, ResourceUsage.Input)(Resource())
      yield ()
    val document = DocInterpreters.run(program, seed)
    val entries = DocInterpreters.trace(program).toList
    assert(document.resourceSets.size == 1)
    assert(entries.nonEmpty)
    assert(DocInterpreters.dryRun(program).isRight)
end DocDslChecks
