package xjdf4s.model.generators

import scala.util.Random

import xjdf4s.core.*
import xjdf4s.model.*
import xjdf4s.model.resources.*

/**
 * Deterministic, XSD-safe generators for the codec property tests.
 *
 * They live in the model TEST scope because they are domain concerns: downstream modules reuse them through
 * `dependsOn(model % "test->test")` (see the sbt multi-project guide in `reference/sbt`, section "Per-configuration
 * classpath dependencies").
 *
 * "XSD-safe" means: values deliberately stay inside the subset the checked-in `schema.xsd` accepts. Fields where
 * the normative tables supersede the stale XSD (`@Version` 2.2, `Media/@MediaColorName`, `Part/@BlockName`,
 * `ResourceSet/@CombinedProcessIndex`, `Tool` 2.2 attributes, `Patch/@SpotType`, newer enum values, ...) are left
 * unset by these generators. The full normative surface is covered by the plain round-trip suites instead.
 */
final class XjdfGenerators(seed: Long):

  private val rng = new Random(seed)
  private var counter = 0

  private def nextName(prefix: String): String =
    counter += 1
    s"$prefix$counter"

  def nmtoken(prefix: String = "tok"): Nmtoken = Nmtoken.from(nextName(prefix)).toOption.get
  def xsdId(prefix: String = "id"): XsdId = XsdId.from(nextName(prefix)).toOption.get
  def xsdIdRef(prefix: String = "ref"): XsdIdRef = XsdIdRef.from(nextName(prefix)).toOption.get
  def string(prefix: String = "text"): XjdfString = XjdfString.from(nextName(prefix)).toOption.get

  def int(low: Int, high: Int): Int = low + rng.nextInt(high - low + 1)
  def float(low: Float, high: Float): Float = low + rng.nextFloat() * (high - low)
  def bool: Boolean = rng.nextBoolean()
  def pick[A](values: A*): A = values(rng.nextInt(values.length))
  def maybe[A](probability: Double)(value: => A): Option[A] =
    if rng.nextDouble() < probability then Some(value) else None

  /** Optional value that is itself optional (flattens the double Option of smart-constructor results). */
  def maybeValue[A](probability: Double)(value: Option[A]): Option[A] =
    if rng.nextDouble() < probability then value else None

  /** Optional vector field: either a 1..maxSize collection or the empty default. */
  def maybeVector[A](probability: Double, maxSize: Int)(value: => A): Vector[A] =
    if rng.nextDouble() < probability then Vector.fill(1 + rng.nextInt(maxSize))(value) else Vector.empty
  def vector[A](maxSize: Int)(value: => A): Vector[A] =
    Vector.fill(rng.nextInt(maxSize + 1))(value)

  def dateTime: XsdDateTime =
    XsdDateTime.from(s"2026-08-17T12:${"%02d".format(int(0, 59))}:00+03:00").toOption.get
  def uri: UriRef = UriRef.from(s"https://example.org/${nextName("file")}").toOption.get

  // -- document surface ---------------------------------------------------------

  def part(): Part =
    Part(
      lotId = maybe(0.6)(nmtoken("lot")),
      sheetName = maybe(0.4)(nmtoken("sheet")),
      side = maybe(0.3)(pick(Side.Front, Side.Back)),
    )

  def comment(): Comment = Comment("generated by property test")

  def glue(): Glue =
    Glue(
      areaGlue = maybe(0.5)(bool),
      glueType = maybe(0.5)(pick(GlueType.ColdGlue, GlueType.Hotmelt, GlueType.Removable)),
      glueLineWidth = maybe(0.3)(float(0.1f, 10f)),
    )

  def media(depth: Int = 0): Media =
    Media(
      mediaType = pick(MediaType.Paper, MediaType.Film, MediaType.Plate, MediaType.Transparency, MediaType.Textile),
      weight = maybe(0.5)(float(10f, 300f)),
      thickness = maybe(0.4)(float(1f, 1000f)),
      mediaUnit = maybe(0.4)(pick(MediaUnit.Sheet, MediaUnit.Roll)),
      mediaLayers = if depth < 2 then maybe(0.3)(mediaLayers(depth + 1)) else None,
    )

  def mediaLayers(depth: Int): MediaLayers =
    MediaLayers(
      Vector(
        MediaLayer.MediaLayer(media(depth)),
        MediaLayer.GlueLayer(glue()),
        MediaLayer.MediaLayer(media(depth)),
      ),
    )

  def color(): Color =
    Color(
      density = maybe(0.5)(float(0f, 2f)),
      gray = maybe(0.5)(float(0f, 1f)),
      lab = maybeValue(0.4)(LabColor.from(float(0f, 100f), float(-100f, 100f), float(-100f, 100f)).toOption),
    )

  def component(mediaRefTarget: XsdId): Component =
    Component(
      surfaceCount = maybe(0.5)(int(1, 8)),
      windingResult = maybe(0.4)(int(0, 1)),
      mediaRef = maybe(0.5)(XsdIdRef.from(mediaRefTarget.value).toOption),
    )

  def tool(): Tool =
    Tool(toolType = maybe(0.5)(nmtoken("toolType")))

  def runList(): RunList =
    // @Pages only: the XSD spells the page-count attribute @NPage while the derived encoder writes @NumberOfPages,
    // a documented naming divergence; the XSD-safe subset leaves it unset.
    RunList(
      pages = maybe(0.5)(IntegerRange(0, int(1, 50))),
    )

  def registerMark(): RegisterMark =
    RegisterMark(markName = maybe(0.5)(nmtoken("mark")), rotation = maybe(0.4)(float(0f, 360f)))

  def specificResource(mediaRefTarget: XsdId): SpecificResource =
    pick[SpecificResource](media(), color(), component(mediaRefTarget), tool(), runList(), registerMark())

  def resource(mediaRefTarget: XsdId): Resource =
    Resource(
      id = maybe(0.5)(xsdId("res")),
      externalId = maybe(0.5)(nmtoken("ext")),
      parts = vector(2)(part()),
      comments = maybeVector(0.3, 1)(comment()),
      specificResource = Some(specificResource(mediaRefTarget)),
    )

  def resourceSet(): ResourceSet =
    // The anchor Resource owns an @ID; every Component/@MediaRef references it, so ID/IDREF stays bound
    // inside the document (XSD constraint cvc-id.1).
    val targetId = xsdId("target")
    val anchor = Resource(id = Some(targetId))
    ResourceSet(
      nmtoken("set"),
      usage = maybe(0.6)(pick(ResourceUsage.Input, ResourceUsage.Output)),
      resources = anchor +: Vector.fill(1 + rng.nextInt(2))(resource(targetId)),
    )

  def xjdf(): XJDF =
    XJDF(
      jobId = nmtoken("job"),
      types = NonEmptyVector.one(nmtoken("process")),
      resourceSets = Vector.fill(1 + rng.nextInt(2))(resourceSet()),
      descriptiveName = maybe(0.4)(string("desc")),
      comments = maybeVector(0.3, 1)(comment()),
    )
end XjdfGenerators
